### ISSUE TITLE
hamburger-nav-drawer-ui

### ISSUE THREAD

**Issue by lsollis** [NutriSnap/NutriSnap#14]
# Shared Navigation Pop-up Menu

This is a sidebar drawer that pops out and makes it easy to navigate between any page. The documentation for this is outdated and doesn't seem to work for MD3, but it does still work.

Task(s):
- [x] Create a mockup of the drawer in [dartpad.dev](https://dartpad.dev/?id=86b3afc420b161e44025128c6a7a9c76)
- [x] Integrate into the main app ui

Design Reference: [Figma-Nav-Drawer](https://www.figma.com/file/AmQ06V53LeGerZum8HGeom/NutriSnap-Hi-Fidelity?type=design&node-id=55-5472&mode=design&t=cF9CddGkow8twtfH-4)

![Image](https://github.com/NutriSnap/NutriSnap/assets/60171929/5f7f9dda-c240-4756-a1d0-20732ff382f2)

**Comment by mlr77** [comment]
I think I'll integrate this using the skeleton app version so I'll need to build from that template first. Also, I need to find a way to allow the image links to be viewable. Strange that they're not visible now...
