### ISSUE TITLE
bottom-nav-bar-ui

### ISSUE THREAD

**Issue by lsollis** [NutriSnap/NutriSnap#15]
# Bottom Navigation Bar

Task(s):
- [x] Create a mock-up of the navigation bar in Dart/Flutter
- [x] Integrate into our NutriSnap app. 

Design Reference: [Figma-Shared-Bottom-Nav-Bar](https://www.figma.com/file/AmQ06V53LeGerZum8HGeom/NutriSnap-Hi-Fidelity?type=design&node-id=60-5887&mode=design&t=cF9CddGkow8twtfH-4)

Mockup:
![Image](https://github.com/NutriSnap/NutriSnap/assets/60171929/d201d4f2-e166-4575-98bb-c93ea63f19d4)

**Comment by mlr77** [comment]
We can close for now and create a new issue if we need to re-attack.
