### ISSUE TITLE
new-snap-page-ui

### ISSUE THREAD

**Issue by mlr77** [NutriSnap/NutriSnap#27]
# Snap Page

This page is intended to be simple and intuitive. The AppBar has three items, Cancel Snap (X), Title, and An upload link. There is a text box to tell the user what to do. A choose photo from library button which converts to the image itself when loaded, and a text input box below to allow the user to add the food type(s).

Task:
 - [ ] Create the UI for the alpha version (as picture below)

![Image](https://github.com/NutriSnap/NutriSnap/assets/60171929/88ce49ef-f996-46b1-868a-66e84bf23a87)

**Comment by lsollis** [comment]
Can't get the default top and bottom app bars to show up
