### ISSUE TITLE
snap-page-functionality

### ISSUE THREAD

**Issue by mlr77** [NutriSnap/NutriSnap#28]
# Snap Page

This page is intended to be simple and intuitive. The AppBar has three items, Cancel Snap (X), Title, and An upload link. There is a text box to tell the user what to do. A choose photo from library button which converts to the image itself when loaded, and a text input box below to allow the user to add the food type(s).

Task:
 - [x] Add the functionality to access the user's photo library.
 - [x] update widgets to access default data in models
 - [ ] Add the state to store the photo and foot types as a database entry.
 - [ ] Upload the information (labeled data and photo) to a cloud storage, if possible.

![Image](https://github.com/NutriSnap/NutriSnap/assets/60171929/88ce49ef-f996-46b1-868a-66e84bf23a87)

**Comment by lsollis** [comment]
"Done" for phase 2 implementation - will need to reopen for phases 3+
